# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernote',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pub_time'], 'verbose_name': '\u901a\u77e5\u53d1\u5e03', 'verbose_name_plural': '\u901a\u77e5\u53d1\u5e03'},
        ),
        migrations.DeleteModel(
            name='UserNote',
        ),
    ]
