# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestroes',
            name='file_content',
            field=models.FileField(upload_to='file/%Y/%m', verbose_name='\u6587\u4ef6'),
        ),
    ]
