# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180411_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestroes',
            name='file_content',
            field=models.FileField(upload_to='file/%Y/%m/%d', verbose_name='\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/images/head/default.png', upload_to='static/images/head/'),
        ),
    ]
