# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_questions_select_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSocre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuanze_score', models.FloatField(blank=True, verbose_name='\u9009\u62e9\u5206\u503c')),
                ('panduan_score', models.FloatField(blank=True, verbose_name='\u5224\u65ad\u5206\u503c')),
                ('jianda_score', models.FloatField(blank=True, verbose_name='\u7b80\u7b54\u5206\u503c')),
                ('paper_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.PaperList', verbose_name='\u6240\u5c5e\u8bd5\u5377\u5206\u503c')),
            ],
        ),
    ]
