# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_papersocre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papersocre',
            options={'ordering': ['id'], 'verbose_name': '\u8bd5\u5377\u5206\u503c\u8868', 'verbose_name_plural': '\u8bd5\u5377\u5206\u503c\u8868'},
        ),
    ]
